import { RandomDataGenerator } from "../utils/randomDataGenerator";

export const mirPayload = {
    materialCode: "",
    materialName: RandomDataGenerator.getRandomMaterialName(),
    description: "raw material",
    erpCode: "",
    materialCategoryId: 76,
    materialTypeId: 75,
    purchaseUomId: null,
    inventoryUomId: null,
    minimumOrderQuantity: 0,
    materialColorId: 0,
    materialFinishId: 0,
    materialThickness: 2.5,
    materialWeight: null,
    materialHeight: null,
    materialLength: 1220,
    materialDiameter: null,
    materialShelfLife: null,
    hsCodeId: 0,
    materialNatureId: [32],
    vendorId: [],
    standardPrice: 10,
    status: true,
    linkWithAssetId: 0,
    taxId: null,
    taxValue: null,
}