import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.locator('div').filter({ hasText: /^Sales$/ }).locator('img').click();
  await page.locator('#root').getByText('Sales Enquiry').click();
  await page.locator('.flex.items-center.justify-between.w-full').first().click();
  await page.getByRole('button', { name: 'Sales Enquiry' }).click();
  await page.getByRole('textbox', { name: 'Customer Name*' }).click();
  await page.getByRole('textbox', { name: 'Customer Name*' }).fill('Tester user ');
  await page.getByRole('textbox', { name: 'Flat / Villa' }).click();
  await page.getByRole('textbox', { name: 'Flat / Villa' }).fill('flat 2');
  await page.getByRole('textbox', { name: 'Building' }).click();
  await page.getByRole('textbox', { name: 'Building' }).fill('building 2');
  await page.getByRole('textbox', { name: 'Block' }).click();
  await page.getByRole('textbox', { name: 'Road' }).click();
  await page.getByRole('textbox', { name: 'Road' }).fill('road 2');
  await page.getByRole('textbox', { name: 'Block' }).click();
  await page.getByRole('textbox', { name: 'Block' }).fill('block 2');
  await page.getByRole('textbox', { name: 'Area' }).click();
  await page.getByRole('textbox', { name: 'Area' }).fill('area 2');
  await page.locator('div:nth-child(6) > .flex > .MuiInputBase-root').first().click();
  await page.getByRole('spinbutton', { name: 'Telephone Number 1' }).fill('987654321');
  await page.getByPlaceholder('Enter Mobile Number 1').click();
  await page.getByPlaceholder('Enter Mobile Number 1').fill('987654321');
  await page.getByRole('spinbutton', { name: 'Fax' }).click();
  await page.getByRole('spinbutton', { name: 'Fax' }).fill('2');
  await page.getByRole('spinbutton', { name: 'Telephone Number 2' }).click();
  await page.getByRole('spinbutton', { name: 'Telephone Number 2' }).fill('896745321');
  await page.getByRole('textbox', { name: 'Email 1' }).click();
  await page.getByRole('textbox', { name: 'Email 1' }).fill('xyz@gmail.com');
  await page.getByRole('textbox', { name: 'Email 2' }).click();
  await page.getByRole('textbox', { name: 'P.O. Box' }).click();
  await page.getByRole('combobox', { name: 'Country' }).click();
  await page.getByRole('option', { name: 'China' }).click();
  await page.getByRole('combobox', { name: 'State' }).click();
  await page.getByText('Guangdong Province').click();
  await page.getByRole('combobox', { name: 'City' }).click();
  await page.getByRole('option', { name: 'Guangdong' }).click();
  await page.getByRole('textbox', { name: 'Project Name' }).click();
  await page.getByRole('textbox', { name: 'Project Name' }).fill('Sales Enquiry Test');
  await page.locator('div').filter({ hasText: /^NormalUrgent$/ }).locator('div').first().click();
  await page.locator('div').filter({ hasText: /^IndoorOutdoor$/ }).locator('div').nth(1).click();
  await page.locator('div').filter({ hasText: /^Promotional \(3 to 6 Month\)Long term \(1 to 2 Year\)$/ }).locator('div').nth(1).click();
  await page.locator('div:nth-child(4) > .p-\\[18px\\].undefined > .grid > div > .flex.flex-col > .flex.\\!gap-8 > label > .w-4').first().click();
  await page.getByRole('textbox', { name: 'Material Thickness' }).click();
  await page.getByRole('textbox', { name: 'Material Thickness' }).fill('54');
  await page.getByRole('textbox', { name: 'Size (Dimension)' }).click();
  await page.getByRole('textbox', { name: 'Size (Dimension)' }).fill('2');
  await page.getByRole('textbox', { name: 'Color/Finish' }).click();
  await page.getByRole('textbox', { name: 'Color/Finish' }).fill('red');
  await page.locator('div').filter({ hasText: /^Supply OnlyInstallation OnlySupply & Installation$/ }).locator('div').first().click();
  await page.getByRole('textbox', { name: 'Wall finishing Details' }).click();
  await page.getByRole('textbox', { name: 'Wall finishing Details' }).fill('glass');
  await page.getByRole('combobox', { name: 'Type Of Equipment Required' }).click();
  await page.getByRole('option', { name: 'Cradle' }).click();
  await page.locator('section').filter({ hasText: 'Is the Permission required:' }).click();
  await page.getByRole('textbox', { name: 'Equipment Provided by' }).click();
  await page.getByRole('textbox', { name: 'Equipment Provided by' }).fill('iron');
  await page.locator('section').filter({ hasText: 'Is the Permission required:' }).locator('div').nth(3).click();
  await page.getByRole('textbox', { name: 'Power Supply' }).click();
  await page.getByRole('textbox', { name: 'Power Supply' }).fill('yes');
  await page.getByRole('combobox', { name: 'Select products*' }).click();
  await page.getByRole('option', { name: 'Embroidery & Tailoring' }).click();
  await page.getByRole('option', { name: 'ATM Products' }).click();
  await page.getByRole('button', { name: 'Choose date' }).first().click();
  await page.getByText('19').click();
  await page.getByRole('combobox', { name: 'Payment Terms*' }).click();
  await page.getByText('% Advance Full Payment').click();
  await page.getByRole('combobox', { name: 'Supply Type*' }).click();
  await page.getByRole('option', { name: 'Local' }).click();
  await page.getByRole('button', { name: 'Choose date', exact: true }).click();
  await page.getByText('19').click();
  await page.getByRole('button', { name: 'Create Enquiry' }).click();
  await page.getByRole('paragraph').filter({ hasText: 'Sales enquiry upserted' }).click();
  await page.getByRole('combobox', { name: 'Category' }).click();
  await page.getByRole('option', { name: 'Badges' }).click();
  await page.locator('.grid').first().click();
  await page.getByRole('combobox', { name: 'Material / Finish' }).click();
  await page.getByRole('option', { name: 'Back Stiff' }).click();
  await page.locator('.grid').first().click();
  await page.getByRole('combobox', { name: 'Tailoring Options' }).click();
  await page.getByRole('option', { name: 'Flags' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('paragraph').filter({ hasText: 'Embroidery tailoring created' }).click();
  await page.getByRole('combobox', { name: 'Aluminium' }).click();
  await page.getByRole('option', { name: 'Painted' }).click();
  await page.getByRole('combobox', { name: 'Stainless Steel' }).click();
  await page.getByRole('option', { name: 'Mirror Finish' }).click();
  await page.getByRole('combobox', { name: 'Brass' }).click();
  await page.getByRole('option', { name: 'Gold Plated' }).click();
  await page.getByRole('combobox', { name: 'Titanium Steel' }).click();
  await page.getByRole('option', { name: 'Gold Mirror' }).click();
  await page.getByRole('combobox', { name: 'Copper' }).click();
  await page.getByRole('option', { name: 'Brush' }).click();
  await page.locator('div:nth-child(2) > .p-0 > div:nth-child(3) > .grid.grid-cols-4').click();
  await page.getByRole('combobox', { name: 'Illumination Options' }).click();
  await page.getByRole('option', { name: 'Led Module' }).click();
  await page.locator('div:nth-child(2) > .p-0 > div:nth-child(3) > .grid.grid-cols-4').click();
  await page.getByRole('combobox', { name: 'Mounting Options' }).click();
  await page.getByRole('option', { name: 'Panel Mount' }).click();
  await page.getByRole('combobox', { name: 'Mounting Options' }).click();
  await page.getByRole('option', { name: 'Spacers' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('paragraph').filter({ hasText: 'Atm products created' }).click();
});